// Code generated by ent, DO NOT EDIT.

package ent

// CreateBlogInput represents a mutation input for creating blogs.
type CreateBlogInput struct {
	Title string
}

// Mutate applies the CreateBlogInput on the BlogMutation builder.
func (i *CreateBlogInput) Mutate(m *BlogMutation) {
	m.SetTitle(i.Title)
}

// SetInput applies the change-set in the CreateBlogInput on the BlogCreate builder.
func (c *BlogCreate) SetInput(i CreateBlogInput) *BlogCreate {
	i.Mutate(c.Mutation())
	return c
}
