// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (b *Blog) Tags(ctx context.Context) (result []*Tag, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = b.NamedTags(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = b.Edges.TagsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = b.QueryTags().All(ctx)
	}
	return result, err
}

func (t *Tag) Blogs(ctx context.Context) (result []*Blog, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = t.NamedBlogs(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = t.Edges.BlogsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = t.QueryBlogs().All(ctx)
	}
	return result, err
}
