version: "3"

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d

  go:
    image: golang:1.20
    ports:
      - "8081:8081"
    environment:
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ENV=${ENV}
    volumes:
      - ./server:/app
    depends_on:
      - mysql
    working_dir: /app
    command: go run ./cmd/server

volumes:
  mysql_data:
