version: "3"

services:
  postgres:
    image: postgres:15.2
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    mem_limit: 512m

  go:
    image: golang:1.20
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ENV=${ENV}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./server:/app
    depends_on:
      - postgres
    working_dir: /app
    command: go run main.go
    mem_limit: 512m

  node:
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    build:
      context: ./client
      dockerfile: Dockerfile
    command: pnpm dev

volumes:
  postgres_data:
