version: '3'

services:
  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    env_file:
      - .env.development
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
