version: '3'

services:
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    env_file:
      - .env.development
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
