version: "3"

services:
  postgres:
    image: postgres:15.2
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  go:
    image: golang:1.20
    ports:
      - "8081:8081"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ENV=${ENV}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./server:/app
    depends_on:
      - postgres
    working_dir: /app
    command: go run ./cmd/server

volumes:
  postgres_data:
