// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Blog struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
	Content     string `json:"content"`
	Tags        []*Tag `json:"tags"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
	PublishedAt string `json:"publishedAt"`
}

type BlogInput struct {
	Title       string      `json:"title"`
	Slug        string      `json:"slug"`
	Description string      `json:"description"`
	Content     string      `json:"content"`
	Tags        []*TagInput `json:"tags"`
	PublishedAt string      `json:"publishedAt"`
}

type LoginPayload struct {
	Token string `json:"token"`
}

type Tag struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type TagInput struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}
