// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Blog struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Slug        string  `json:"slug"`
	Description string  `json:"description"`
	Content     string  `json:"content"`
	Tags        []*Tag  `json:"tags"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
	PublishedAt *string `json:"publishedAt,omitempty"`
}

type BlogInput struct {
	Title       string      `json:"title"`
	Slug        string      `json:"slug"`
	Description string      `json:"description"`
	Content     string      `json:"content"`
	Tags        []*TagInput `json:"tags"`
	Published   bool        `json:"published"`
}

type BlogList struct {
	Data  []*Blog `json:"data"`
	Total int     `json:"total"`
}

type BlogListInput struct {
	Limit  int      `json:"limit"`
	Offset int      `json:"offset"`
	Tags   []string `json:"tags,omitempty"`
}

type LoginPayload struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type Tag struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type TagInput struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}
