// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package server

type LoginInput struct {
	Password string `json:"password"`
}

type LoginPayload struct {
	Token string `json:"token"`
}
