package server

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.27

import (
	"context"
	"fmt"
	"log"

	"github.com/sor4chi/portfolio-blog/server/ent"
	"github.com/sor4chi/portfolio-blog/server/ent/blog"
)

// CreateBlog is the resolver for the createBlog field.
func (r *mutationResolver) CreateBlog(ctx context.Context, input ent.CreateBlogInput) (*ent.Blog, error) {
	log.Println("CreateBlogCtx", ctx)
	// service.JwtValidate(ctx, "token")
	return r.client.Blog.Create().SetInput(input).Save(ctx)
}

// ShowBlog is the resolver for the showBlog field.
func (r *mutationResolver) ShowBlog(ctx context.Context, slug string) (*ent.Blog, error) {
	return r.client.Blog.Query().Where(blog.Slug(slug)).Only(ctx)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input LoginInput) (*LoginPayload, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
