import '@/style/globals.css';
import { VanillaLayout } from '@/ui/app/layout/vanilla';

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function LandingLayout({ children }: { children: React.ReactNode }) {
  return <VanillaLayout>{children}</VanillaLayout>;
}
