// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BlogsColumns holds the columns for the "blogs" table.
	BlogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString, Size: 64},
		{Name: "slug", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "description", Type: field.TypeString, Size: 256},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
	}
	// BlogsTable holds the schema information for the "blogs" table.
	BlogsTable = &schema.Table{
		Name:       "blogs",
		Columns:    BlogsColumns,
		PrimaryKey: []*schema.Column{BlogsColumns[0]},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 64},
		{Name: "slug", Type: field.TypeString, Unique: true, Size: 64},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
	}
	// TagBlogsColumns holds the columns for the "tag_blogs" table.
	TagBlogsColumns = []*schema.Column{
		{Name: "tag_id", Type: field.TypeInt},
		{Name: "blog_id", Type: field.TypeInt},
	}
	// TagBlogsTable holds the schema information for the "tag_blogs" table.
	TagBlogsTable = &schema.Table{
		Name:       "tag_blogs",
		Columns:    TagBlogsColumns,
		PrimaryKey: []*schema.Column{TagBlogsColumns[0], TagBlogsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tag_blogs_tag_id",
				Columns:    []*schema.Column{TagBlogsColumns[0]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "tag_blogs_blog_id",
				Columns:    []*schema.Column{TagBlogsColumns[1]},
				RefColumns: []*schema.Column{BlogsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BlogsTable,
		TagsTable,
		TagBlogsTable,
	}
)

func init() {
	TagBlogsTable.ForeignKeys[0].RefTable = TagsTable
	TagBlogsTable.ForeignKeys[1].RefTable = BlogsTable
}
