import { themeClass } from '@/style/theme.css';
import '@/style/globals.css';

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // observe body class, if it is changed, then change theme
  return (
    <>
      <head>
        {/* eslint-disable-next-line @next/next/no-sync-scripts */}
        <script src="/theme.js" />
      </head>
      <html lang="ja">
        <body className={themeClass}>{children}</body>
      </html>
    </>
  );
}
