import { FullLayout } from "@/app/ui/app/layout/full";
import { themeClass } from "./style/theme.css";
import "./style/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // observe body class, if it is changed, then change theme
  return (
    <>
      <head>
        {/* eslint-disable-next-line @next/next/no-sync-scripts */}
        <script src="/theme.js" />
      </head>
      <html lang="ja">
        <body className={themeClass}>
          <FullLayout>{children}</FullLayout>
        </body>
      </html>
    </>
  );
}
