import { FullLayout } from '@/ui/app/layout/full';
import '@/style/globals.css';

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function PortfolioLayout({ children }: { children: React.ReactNode }) {
  return <FullLayout>{children}</FullLayout>;
}
