import { FullLayout } from '@/ui/app/layout/full';
import { themeClass } from '@/style/theme.css';
import '@/style/globals.css';
import { VanillaLayout } from '@/ui/app/layout/vanilla';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function PortfolioLayout({ children }: { children: React.ReactNode }) {
  return <FullLayout>{children}</FullLayout>;
}
