// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"database/sql"
	"time"
)

type Blog struct {
	ID          int32
	Title       string
	Description string
	Slug        string
	Content     string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	PublishedAt sql.NullTime
}

type BlogsTag struct {
	BlogID int32
	TagID  int32
}

type SchemaMigration struct {
	Version string
}

type Tag struct {
	ID        int32
	Name      string
	Slug      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Timeline struct {
	ID            int32
	Title         string
	RelatedBlogID sql.NullInt32
	Category      int32
	Date          time.Time
}
