// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"database/sql"
	"time"
)

type Blog struct {
	// blog id
	ID int32
	// blog title
	Title string
	// blog slug
	Slug string
	// blog content
	Content string
	// blog created at
	CreatedAt time.Time
	// blog updated at
	UpdatedAt time.Time
	// blog published at, null if not published
	PublishedAt sql.NullTime
}

type BlogsTag struct {
	// blog id
	BlogID int32
	// tag id
	TagID int32
}

type SchemaMigration struct {
	Version string
}

type Tag struct {
	// tag id
	ID int32
	// tag name
	Name string
	// tag slug
	Slug string
	// tag created at
	CreatedAt time.Time
	// tag updated at
	UpdatedAt time.Time
}
