// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: tag.sql

package sqlc

import (
	"context"
)

const getTagsBySlugs = `-- name: GetTagsBySlugs :many
SELECT id, name, slug, created_at, updated_at FROM tags WHERE slug IN (?)
`

func (q *Queries) GetTagsBySlugs(ctx context.Context, slug string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsBySlugs, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
